version: '3.8'

services:
  mongo:
    image: mongo
    container_name: url_mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: shortener_mongo_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: url_redis_container
    restart: always
    command: redis-server --requirepass shortener_redis_password
    ports:
      - "6379:6379"

volumes:
  mongo_data: